### ISSUE TITLE
Cannot read property 'destroy' of undefined

### ISSUE THREAD

**Issue by guyellis** [ericadamski/collaborative-edit#23]
[Enter steps to reproduce below:]
1. Press Ctrl+Shft+Alt+c

**Atom Version**: 0.194.0
**System**: linux 3.16.0-36-generic
**Thrown From**: [collaborative-edit](https://github.com/ericadamski/collaborative-edit) package, v0.2.6
### Stack Trace

Uncaught TypeError: Cannot read property 'destroy' of undefined

```
At /home/guy/.atom/packages/collaborative-edit/lib/Client/client.coffee:88

TypeError: Cannot read property 'destroy' of undefined
  at Object.client.deactivate (/home/guy/.atom/packages/collaborative-edit/lib/Client/client.coffee:88:25)
  at CollaborativeEditView.module.exports.CollaborativeEditView.destroy (/home/guy/.atom/packages/collaborative-edit/lib/collaborative-edit-view.coffee:114:12)
  at CollaborativeEditView.module.exports.CollaborativeEditView.Disconnect (/home/guy/.atom/packages/collaborative-edit/lib/collaborative-edit-view.coffee:134:6)
  at atom-workspace.<anonymous> (/home/guy/.atom/packages/collaborative-edit/lib/collaborative-edit-view.coffee:109:69)
  at atom-workspace.handler (/usr/share/atom/resources/app.asar/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:178:20)

```
### Commands

```
     -4:49.2.0 application:add-project-folder (atom-text-editor.editor)
  2x -4:28.6.0 key-binding-resolver:toggle (ul.list-inline.tab-bar.inset-panel)
     -4:26.8.0 settings-view:open (ul.list-inline.tab-bar.inset-panel)
 28x -4:17.5.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -4:12.1.0 core:move-up (atom-text-editor.editor.is-focused)
 21x -4:11.2.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:41.3.0 collaborative-edit:Host (atom-text-editor.editor.is-focused)
     -0:44.8.0 mocha-test-runner:debug (atom-text-editor.editor.is-focused)
     -0:00.5.0 collaborative-edit:Disconnect (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "linter-jshint"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
collaborative-edit, v0.2.6
linter, v0.12.1
linter-eslint, v0.5.3
minimap, v4.8.0
mocha-test-runner, v0.4.0

# Dev
No dev packages
```

**Comment by ericadamski** [comment]
@guyellis I am currently updating everything to work with the newest version of Atom, and also conforming to the newer API guidelines.

**Comment by guyellis** [comment]
:+1:
