### ISSUE TITLE
Failed to activate the collaborative-edit package

### ISSUE THREAD

**Issue by chrisbain-knd** [ericadamski/collaborative-edit#24]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Ubuntu 15.04
**Thrown From**: [collaborative-edit](https://github.com/ericadamski/collaborative-edit) package, v0.2.6
### Stack Trace

Failed to activate the collaborative-edit package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/home/csbain/.atom/packages/collaborative-edit/lib/collaborative-edit-view.coffee:4:199)
    at /home/csbain/.atom/packages/collaborative-edit/lib/collaborative-edit-view.coffee:31:5
    at Object.<anonymous> (/home/csbain/.atom/packages/collaborative-edit/lib/collaborative-edit-view.coffee:59:5)
    at Object.<anonymous> (/home/csbain/.atom/packages/collaborative-edit/lib/collaborative-edit-view.coffee:271:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/usr/share/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```
### Commands

```
     -0:00.6.0 collaborative-edit:Host (atom-text-editor.editor.is-focused)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
collaborative-edit, v0.2.6
motepair, v0.20.0

# Dev
No dev packages
```

**Comment by ericadamski** [comment]
The API on the package is out of date, working to updated it!
